# Generated by Django 5.1.1 on 2024-10-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_temporary_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(default='https://github.com/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='skill_requirements',
            field=models.CharField(default='Communication', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='skills_gained',
            field=models.CharField(default='HTML', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='topic',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('AI', 'AI'), ('Data Science', 'Data Science'), ('Cybersecurity', 'Cybersecurity')], default='CSS', max_length=100),
            preserve_default=False,
        ),
    ]
