# Generated by Django 5.1.1 on 2024-10-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_userprofile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
