# Generated by Django 5.1.1 on 2024-10-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
