# Generated by Django 5.1.1 on 2024-10-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_comment_user_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
