# Generated by Django 5.1.3 on 2024-11-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_userprofile_concentration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Software Engineering', 'Software Engineering'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Data Science', 'Data Science'), ('Cybersecurity', 'Cybersecurity'), ('Robotics', 'Robotics'), ('Game Development', 'Game Development')], max_length=100),
        ),
    ]
