# Generated by Django 5.1.3 on 2024-12-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
