# Generated by Django 5.1.3 on 2024-12-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_skills_userprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='concentration',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Data Science', 'Data Science'), ('Cybersecurity', 'Cybersecurity'), ('Software Engineering', 'Software Engineering'), ('Robotics', 'Robotics'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=200),
        ),
    ]
