# Generated by Django 5.1.1 on 2024-11-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_notification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='concentration',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Data Science', 'Data Science'), ('Cybersecurity', 'Cybersecurity'), ('Software Engineering', 'Software Engineering')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade_level',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], max_length=50),
        ),
    ]
