# Generated by Django 5.1.3 on 2025-01-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='banner_pics/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
