# Generated by Django 5.1.1 on 2024-11-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
