# Generated by Django 5.1.3 on 2025-02-09 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_topic_trainingpost_delete_trainingregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='trainingpost',
            options={},
        ),
        migrations.RenameField(
            model_name='trainingpost',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='trainingpost',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='trainingpost',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='trainingpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='trainingpost',
            name='updated',
        ),
        migrations.AlterField(
            model_name='trainingpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingpost',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='projects.trainingtopic'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='projects.trainingpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
