# Generated by Django 5.1.3 on 2025-02-15 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_rename_like_traininglike_trainingcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project Created'), ('project_joined', 'Project Joined'), ('project_completed', 'Project Completed'), ('comment_added', 'Comment Added'), ('followed_user', 'Followed a User'), ('training_posted', 'Training Posted')], max_length=50),
        ),
        migrations.CreateModel(
            name='SkillEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'profile', 'skill')},
            },
        ),
    ]
