# Generated by Django 5.1.3 on 2025-02-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_project_github_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='link_preview',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
