# Generated by Django 5.1.1 on 2025-04-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_message_options_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cair_hackathon',
            field=models.BooleanField(default=False),
        ),
    ]
